version: '3.9'
services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./nginx/templates:/etc/nginx/templates
     - letsencrypt:/etc/letsencrypt
    environment:
     - DOMAIN=${DOMAIN}
  certbot:
    build: ./certbot-route53
    restart: unless-stopped
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt-lib:/var/lib/letsencrypt
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - DOMAIN=${DOMAIN}
volumes:
  letsencrypt:
  letsencrypt-lib: